name: Check domain expiry
on: [push]

jobs:
  build:
    name: Check zipkin.io
    runs-on: macos-latest
    steps:
      - name: whois
        run:  exit $((($(date -j -f %Y-%m-%dT%H:%M:%SZ "$(whois zipkin.io | awk '/Registry Expiry Date:/ { print $4 }')" +%s) - $(date +%s)) / 3600 / 24 > 30 != 1))
