name: Check domain expiry
on: [push]

jobs:
  build:
    name: Check zipkin.io expiration
    # MacOS comes with whois installed by default
    runs-on: macos-latest
    steps:
      # Exit code 0 is more than 30 days until expiration, 1 otherwise
      - run:  exit $((($(date -j -f %Y-%m-%dT%H:%M:%SZ "$(whois zipkin.io | awk '/Registry Expiry Date:/ { print $4 }')" +%s) - $(date +%s)) / 3600 / 24 > 30 != 0))
      - uses: peter-evans/create-issue-from-file@bbb5be971c8f74166aee89b67be51156dfca5e03
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: zipkin.io domain about to expire
          content-filepath: ./.github/workflows/domain-expired-issue.md
          labels: bug
